# Set a plain language title for the site.
title: USHELP Medical Supply Catalog (Concept)

# Write a short description for the site. This is used for "meta description."
description: We strategically source and manage quality-assured commodities like essential medicines and supplies for HIV/AIDS, malaria, maternal and child health, and reproductive health programs.

# Set the language for the site. Used for "html lang." Default is English.
lang: en

# Add Google Analytics if needed. Replace placeholder with site ID.
ga: UA-XXXXX-Y

# Avoid GitHub API authentication when building locally. (Not working)
github: [metadata]

# Enable for live hosting on GitHub Pages
baseurl: /med-supply-cat

# Use a collection or oganize the product information
collections:
  products:
    output: true
    permalink: /:categories/:title.html
  categories:
    output: true

# Set a short name for the site to use in the header section.
short-title: USHELP MSC